apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  namespace: default
  labels:
    app: prometheus
spec:
  containers:
  - name: prometheus
    image: {{ .Values.prometheus.image }}
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: {{ .Values.prometheus.port }}
  imagePullSecrets:
  - name: {{ .Values.imagePullSecret.name }}

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - name: port-9090
    port: {{ .Values.prometheus.port }}
    targetPort: {{ .Values.prometheus.port }}
    nodePort: {{ .Values.prometheus.nodePort }}