name: Build container image 

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'wrapper_script.sh'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Debug GitHub context
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Repository: ${{ github.repository }}"
          echo "Run number: ${{ github.run_number }}"
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_NAME }}
          password: ${{ secrets.REGISTRY_SECRET }}
      - name: Build Container Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.CONTAINER_REGISTRY }}/ppe-version:latest
            ${{ secrets.CONTAINER_REGISTRY }}/ppe-version:build-${{ github.run_number }}
